#Common setup
- hosts: tag_Node_Master
  vars_prompt:
    - name: SSH_KEY_PATH
      prompt: "Enter path of SSH KEY for master"
      private: no
  roles:
  - role: "k8s_common"

- hosts: tag_Node_Slave
  vars_prompt:
    - name: SSH_KEY_PATH
      prompt: "Enter path of SSH KEY for slave"
      private: no
  roles:
  - role: "k8s_common"

#Master configuration
- hosts: tag_Node_Master
  vars_prompt:
    - name: SSH_KEY_PATH
      prompt: "Enter path of SSH KEY for master"
      private: no
  roles:
  - role: "k8s_master"

#Slave configuration
- hosts: tag_Node_Slave
  vars_prompt:
    - name: SSH_KEY_PATH
      prompt: "Enter path of SSH KEY for slave"
      private: no
  roles:
  - role: "k8s_slave"

#Checking if nodes connected
- hosts: tag_Node_Master
  vars_prompt:
    - name: SSH_KEY_PATH
      prompt: "Enter path of SSH KEY for master"
      private: no
  vars:
    - ansible_user: ec2-user
    - ansible_ssh_private_key_file: "{{ SSH_KEY_PATH }}"
    - ansible_become: true
  tasks:
    - name: "Checking nodes"
      command: "kubectl get nodes"
      register: nodes
    - debug:
        msg: "{{ nodes.stdout_lines }}"
          

